### ISSUE TITLE
How to differentiate between getting a false because there was a mismatch or a deny?

### ISSUE THREAD

**Issue by yaser-ali-s** [Rogger794/iam-policies#10]
I want to be able to know whether the policy returned false because there was a deny, or because the policies don't match actions/resources/principals. Is there a way to do this, logically, or using the two extra functions (getValueFromPath & applyContext) you provide?

Great job with the package otherwise. Works flawlessly and looks amazing. Appreciate the hard work put into it.

**Comment by Rogger794** [comment]
Hi @yaser-ali-s. For nos it doesn't differentiate false value. It returns false in both situations. The only way now is checking the raw policy. getValueFromPath is for getting an attribute from a json and applyContext is used to put json values into a string. I guess that for now is not supported this feature. I would appreciate a pull request if you can or maybe discuss how it can be done.

**Comment by yaser-ali-s** [comment]
Ideally, at least, I would like to be able to run the `can` method for both the allowStatements and denyStatements that are private properties of the `IdentityBasedPolicy` and `ResourceBasedPolicy` classes.

That way, I can distinguish what is happening through the results like so:

| Policy    | canArg   	| Result 	|
|--------	|------------- |--------	|
| allow 	| match    	| true   	|
| allow 	| mismatch 	| false  	|
| deny  	| match    	| false  	|
| deny  	| mismatch 	| true   	|

I can deduce that if the argument checked against the allow policy returned false, it means it wasn't in the allow scope, and vice versa for the deny.

There are four different ways to mitigate this:
- First, I can always filter through my statements and create two policy objects, each only having allow or deny statements.
- Second, we could simply make the denyStatements and allowStatements public to avoid having to filter ourselves, but that would mean that we would have to create three policy objects as opposed to two.
- Third, we could have two methods; namely, `can` for allows and `cannot` for denies.
- Fourth, we could have three methods; namely, `can` for allows, `cannot` for denies, and `evaluate`, which goes through both allow and deny statements.

The reason I want this feature is because I am implementing IAM through different levels of permissions. If a user has a deny in his role, but an allow inlined with his user object, I would like to allow him to access something. The same would go for if his role had an allow, and his user object a deny, in which the more explicit permissions would trump the group/role permissions, and he would be denied access. I do realize this isn't how AWS does it, but I can see user accounts be passed around as a result of it being too much work for admins to create new roles or give explicit permissions because that one group the user belongs to has a deny for that certain action, or even assigning a role with too many permissions to anyone for a specific action.

Let me know your thoughts.

**Comment by yaser-ali-s** [comment]
I'm almost done adding in the new feature. I'll do a pull request soon.
